// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB58eriJ3lInqArbBqlI4UY-lkkcrEicmU',
    appId: '1:890336956924:web:e4a9eab23be335f711e279',
    messagingSenderId: '890336956924',
    projectId: 'moradias-inatel',
    authDomain: 'moradias-inatel.firebaseapp.com',
    storageBucket: 'moradias-inatel.firebasestorage.app',
    measurementId: 'G-0MFPEKXKWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL0aaR1gdW-x3oiH4gxZVNMozISryp5CI',
    appId: '1:890336956924:android:36841d0e1c62cc0011e279',
    messagingSenderId: '890336956924',
    projectId: 'moradias-inatel',
    storageBucket: 'moradias-inatel.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5UScW50NxeC1QPGum5gj4MhUkGcuyPPo',
    appId: '1:890336956924:ios:ea51fa9df84ad72e11e279',
    messagingSenderId: '890336956924',
    projectId: 'moradias-inatel',
    storageBucket: 'moradias-inatel.firebasestorage.app',
    iosBundleId: 'com.example.moradiaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5UScW50NxeC1QPGum5gj4MhUkGcuyPPo',
    appId: '1:890336956924:ios:ea51fa9df84ad72e11e279',
    messagingSenderId: '890336956924',
    projectId: 'moradias-inatel',
    storageBucket: 'moradias-inatel.firebasestorage.app',
    iosBundleId: 'com.example.moradiaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB58eriJ3lInqArbBqlI4UY-lkkcrEicmU',
    appId: '1:890336956924:web:38c587183822da2d11e279',
    messagingSenderId: '890336956924',
    projectId: 'moradias-inatel',
    authDomain: 'moradias-inatel.firebaseapp.com',
    storageBucket: 'moradias-inatel.firebasestorage.app',
    measurementId: 'G-SV0JGBSMH7',
  );
}
